feat: add version of documentation using Material for MkDocs
INTERSECT-training/packaging pull request #65
Opened 2024-06-05 18:13 UTC by hollandjg

- Add a new version of the documentation episode using Material for MkDocs.
- Add a new documentation overview page which outlines that we have sphinx or mkdocs, and you can use either.

- resolves #19

2024-06-06 14:56 UTC, mirestrepo approved these changes
Looks great. I didn't verify all steps, but they all seem expected

2024-06-06 14:56 UTC, mirestrepo commented on _episodes/06.02-documentation-mkdocs-material.md
> +site_url: https://hollandjg.github.io/package
Maybe use `<your github username>` as you did below in other instructions instead of using `hollandjg`?

2024-06-06 14:56 UTC, mirestrepo commented on _episodes/06.02-documentation-mkdocs-material.md
> +`package` is a simple Python library that contains a single function for rescaling arrays.
Is `package` the actual name? What about using an actual name they can just use?

2024-06-06 14:56 UTC, mirestrepo commented on _episodes/06.02-documentation-mkdocs-material.md
> +pip install https://github.com/<your github username>/<the package name>
and the `package` can be explicit here

2024-06-17 17:20 UTC, hollandjg commented on _episodes/06.02-documentation-mkdocs-material.md
> +site_url: https://hollandjg.github.io/package
Good idea.

2024-06-17 17:48 UTC, hollandjg commented on _episodes/06.02-documentation-mkdocs-material.md
> +`package` is a simple Python library that contains a single function for rescaling arrays.
I think we need to unify this across the whole lesson. At the moment it's literally called `package` but perhaps `intersect2024-packaging-example`.

This makes me think too, that even if we choose a better name, we're still going to have collisions when we get to publishing on PyPI – perhaps we need to make it `intersect2024-<your initials>-packaging-example` and point out that when you publish it on github pages, it's the _repository name_ which actually counts, rather than the package name.

2024-06-17 17:48 UTC, hollandjg commented on _episodes/06.02-documentation-mkdocs-material.md
> +pip install https://github.com/<your github username>/<the package name>
updated here also

2024-06-17 18:09 UTC, henryiii commented on _episodes/06.02-documentation-mkdocs-material.md
> +`package` is a simple Python library that contains a single function for rescaling arrays.
I'd publish to test PyPI, or add a `"Private :: Do Not Upload"` classifier, as we don't want to add test packages to PyPI.

2024-06-18 18:58 UTC, hollandjg commented on _episodes/06.02-documentation-mkdocs-material.md
> +`package` is a simple Python library that contains a single function for rescaling arrays.
I agree on the PyPI thing.
- We instruct people to upload to test PyPI, but we would also have collisions there. 
- I've added the "Private :: Do Not Upload" classifier in #60 

The other way of publishing is to push to a git server and install using `pip install git+https://github.com/<username>/<repo name>`. The repo name there is relevant for the path to the GitHub pages docs, not the package name.

2024-06-19 02:16 UTC, henryiii commented on _episodes/06.02-documentation-mkdocs-material.md
> +`package` is a simple Python library that contains a single function for rescaling arrays.
Using their name as part of the package is what we do in https://packaging.python.org/en/latest/tutorials/packaging-projects/ (along with pushing to test PyPI)

2024-07-01 18:09 UTC, hollandjg commented on _episodes/06.02-documentation-mkdocs-material.md
> +`package` is a simple Python library that contains a single function for rescaling arrays.
That's a good idea. I think we'll do that.

2024-07-02 22:31 UTC, hollandjg commented on _episodes/06.02-documentation-mkdocs-material.md
> +`package` is a simple Python library that contains a single function for rescaling arrays.
Since that renaming change is across multiple files, I've made a separate issue #77 
(We'll fix that once all the current PRs are merged.)

2024-07-02 22:33 UTC, hollandjg commented on _episodes/06.02-documentation-mkdocs-material.md
> +site_url: https://hollandjg.github.io/package
Done

2024-07-16 15:29 UTC, gtdang requested changes
Have some comments to make the file edits clearer.

2024-07-16 15:29 UTC, gtdang commented on _episodes/06.2-documentation-mkdocs-material.md
> +  ```
```suggestion
  ```yaml
  # mkdocs.yml
  plugins:
  - mkdocstrings
  ```
```

2024-07-16 15:29 UTC, gtdang commented on _episodes/06.2-documentation-mkdocs-material.md
> +  ```
```suggestion
  ```toml
  # pyproject.toml
  [project.optional-dependencies]
  docs = [
    "mkdocs-material",
    "mkdocstrings[python]"
  ]
  ```
```

2024-07-16 15:29 UTC, gtdang commented on _episodes/06.2-documentation-mkdocs-material.md
> +- Include the `mkdocstrings[python]` package in the `docs` dependencies:
```suggestion
- Include the `mkdocstrings[python]` package in the `docs` dependencies of the pyprojects.toml:
```

2024-07-16 15:29 UTC, gtdang commented on _episodes/06.2-documentation-mkdocs-material.md
> +  ```
The comments to give some clarity which file the code block refers to because the section show editing of 3 different files. Though we can't do this with the markdown code block because it will make a heading if they copy it exactly.... Could be a good teaching moment though?

2024-07-16 15:29 UTC, gtdang commented on _episodes/06.2-documentation-mkdocs-material.md
> +- Reload the documentation preview.
```suggestion
- Reinstall using `pip install --editable ".[docs]"`  since we added a new dependency and reload the documentation preview.
```
A new doc dependency was added to the pyproject.toml so they'll need to pip install again.

2024-07-16 15:29 UTC, gtdang commented on _episodes/06.2-documentation-mkdocs-material.md
> +- Reload the documentation preview.
They may need to kill the previous mkdoc serve process to free port.

2024-07-16 20:22 UTC, hollandjg commented on _episodes/06.2-documentation-mkdocs-material.md
> +  ```
We could use a comment like 
```
<!--- docs/index.md -->
```
rather than the `#` comment – what do you think?

2024-07-16 20:23 UTC, hollandjg commented on _episodes/06.2-documentation-mkdocs-material.md
> +  ```
I've updated the suggestions with ````suggestion (rather than ```suggestion) so they show all the lines.

2024-07-16 20:33 UTC, hollandjg commented on _episodes/06.2-documentation-mkdocs-material.md
> +- Reload the documentation preview.
I've added some extra content here to kill, reinstall, and restart the preview server. Better?

2024-07-16 21:23 UTC, merged